name: RN24-signup test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run test suite
      run: php rn24-signup/test.php

  upload:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir artifact
          cp -R rn24-signup artifact
      - uses: actions/upload-artifact@v1
        with:
          name: rn24-signup
          path: ${{ github.workspace }}/artifact
